### ISSUE TITLE
Refactor this repo to be a Python package

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/ladybug-grasshopper#16]
This will be a major breaking change that we should do at the next release. This will involve isolating the parts of this repo just related to Grasshopper (src and user_objects) and putting them into a folder entitled `ladybug_grasshopper`. We can also add a `samples` folder that contains a set of sample test files.

**Comment by AntoineDao** [comment]
(Sorry my bad. Pressed wrong button on zenhub)

**Comment by chriswmackey** [comment]
This has been addressed via:
https://github.com/ladybug-tools/ladybug-grasshopper/pull/23
