### ISSUE TITLE
Add check for Horizontal infrared radiation in multiple components

### ISSUE THREAD

**Issue by dmitry-ivanov-mm** [ladybug-tools/ladybug-grasshopper#286]
Hi there,

As it is noted in the comments to "Import EPW" component, if Horizontal infrared radiation intensity data is missing in the climate file it will be written as 9999. Currently, the components using the Horizontal infrared radiation do not check for missing data (i.e. 9999) and reading it as 9999 W/m2. Obviously, this makes all the results, which take into account Horizontal infrared radiation incorrect.

I came across this problem while calculating Mean Radiant Temperature with LB Outdoor Solar MRT component (just got incorrect results) and I was not able to run the DF Run Urban Weather Generator at all.

Even though the problem can be fixed with generating the missing values with DF Horizontal Infrared component, it would be great to add automatic checks for the missing Horizontal infrared radiation data and generate reports indicating this issue.

Cheers,
Dmitry

**Comment by chriswmackey** [comment]
Sorry for the late response, @dmitry-ivanov-mm . This is a good suggestion. Let me see if I can implement a check for this case now.

**Comment by chriswmackey** [comment]
I'm merging in the check now. Here is what it will look like:

![image](https://user-images.githubusercontent.com/5567574/160250474-c2f2e8b1-5257-40c8-9cb2-a523b4fa6095.png)

**Comment by dmitry-ivanov-mm** [comment]
Thank you, @chriswmackey. The solution looks great!

A bit of an afterthought: is this problem with using of 9999 for missing values something that is relevant to other components and even to other climate inputs? Sorry, should have asked this earlier.
