### ISSUE TITLE
Wrap ghenv calls in a separate function in ladybug-rhino module

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-grasshopper#33]
In light of having the flexibility to use the Grasshopper component as the base for other platforms I think we should not call `ghenv` methods directly from inside the component.

I suggest to keep all of them in a single module that can be reused among different components.

For example this one can be translated to a `turn_off_output_preview` method similar to the functions that we use to check the component inputs.

https://github.com/ladybug-tools/ladybug-grasshopper/blob/bbee6793ab64c6ece18c7a76aed52e642271e70f/ladybug_grasshopper/src/LB%20SunPath.py#L302

**Comment by AntonelloDN** [comment]
@mostaphaRoudsari 

about "ghenv", I suggest you add `__version__` inside __init__ of main py file.
In this way you can write something like this:
`ghenv.Component.Message = __version__`
If you continue adding them in component you can import version:
`from moduleXYZ import __version__`
component follow always version of module in this way.

**Comment by mostaphaRoudsari** [comment]
Hi @AntonelloDN, Great suggestion but I see two possible issues:

1. We update the version for each component separately until the next major release. This helps to keep updating the definitions easy.

2. If we read the version from a module and not the component itself we can end up with cases that one opens an old Grasshopper file with a newer installation of ladybug libraries and then all the components will be versioned to the latest version. That is not desired.

**Comment by chriswmackey** [comment]
Makes sense. These functions should go into the `grasshopper.py` module of `ladybug_rhino` like [the function that you see here to give a component warning](https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/grasshopper.py#L18-L26)
